// Generated by https://quicktype.io

export interface SearchResult {
    type:               string;
    title?:             string;
    videoId?:           string;
    author:             string;
    authorId:           string;
    authorUrl:          string;
    videoThumbnails?:   Thumbnail[];
    description?:       string;
    descriptionHtml?:   string;
    viewCount?:         number;
    published?:         number;
    publishedText?:     string;
    lengthSeconds?:     number;
    liveNow?:           string;
    paid?:              string;
    premium?:           string;
    playlistId?:        string;
    playlistThumbnail?: string;
    authorVerified?:    boolean;
    videoCount?:        number;
    videos?:            Video[];
    authorThumbnails?:  Thumbnail[];
    autoGenerated?:     string;
    subCount?:          number;
}

export interface Thumbnail {
    url:      string;
    width:    number;
    height:   number;
    quality?: string;
}

export interface Video {
    title:           string;
    videoId:         string;
    lengthSeconds:   number;
    videoThumbnails: Thumbnail[];
}
