export default function Head() {
  return (
    <>
      <title>MiniYT</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="theme-color" content="#1C1C1C"/>
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
