import IINALink from '@/components/IINALink'
import Navbar from '@/components/Navbar'
// import '@/styles/globals.css'
import Head from 'next/head'

export default function HomePage() {
  return (
    // <>Hallo Next.js</>
    <div>
      <Head>
        <title>MiniYT</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#1C1C1C"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />

      <main>
        <IINALink url="https://www.youtube.com/watch?v=lIV8qIKxVkk" />
        <button className="button default-colors">Hallo</button>
      </main>
    </div>
  )
}